Update baggers.js
brownbaglunch/data pull request #133
Opened 2016-09-23 15:32 UTC by brunocatteau

2016-09-24 00:49 UTC, dadoonet commented on baggers.js
> +          "name": "Lucca",
Please look at the README (Websites) and fix accordingly,

2016-09-24 00:50 UTC, dadoonet commented on baggers.js
> +          "name": "Brico-info.com",
Same here

2016-09-24 00:51 UTC, dadoonet requested changes

2016-09-29 14:46 UTC, brunocatteau reviewed
Fixed

2016-09-30 06:50 UTC, dadoonet commented
Hi @brunocatteau 

Could you please rebase on latest master (possibly squash your commits and force push to your repo? So I can merge it?
There is a conflict change for now.

2016-10-05 20:29 UTC, dadoonet commented
Ping?

2016-11-02 07:25 UTC, dadoonet commented
@brunocatteau Can you rebase on master please?

2016-11-02 07:27 UTC, dadoonet commented on baggers.js
> +      "name": "Bruno CATTEAU",
Can you replace with `Bruno Catteau` so it's more consistent with others?

2016-12-19 10:02 UTC, dadoonet commented
Ping?

2017-04-01 20:36 UTC, dadoonet commented
Pas de News. Closing.

2017-04-01 20:36 UTC, closed without merging