Francois Wauquier
brownbaglunch/data pull request #141
Opened 2016-10-05 17:15 UTC by wokier

Passionné prêt à partager autour d'un brown bag lunch

2016-10-05 20:29 UTC, dadoonet requested changes

2016-10-05 20:29 UTC, dadoonet commented on baggers.js
> +            "since": "2016-09-30",
Change to 2016-10-05 please

2016-10-06 11:07 UTC, wokier commented on baggers.js
> +            "since": "2016-09-30",
Done

2016-10-06 11:33 UTC, dadoonet approved these changes

2016-10-06 11:33 UTC, merged