Mise à jour de mes infos, création d'une ville Bayonne
brownbaglunch/data pull request #155
Opened 2016-12-04 22:14 UTC by Yharra

2016-12-05 08:15 UTC, dadoonet requested changes
Please also change the end of this file to add Bayonne:

```
  "cities": {
    "Aix-en-Provence": {
      "name": "Aix-en-Provence",
      "ville_img": "img/villes/BBL.jpg",
      "lat": 43.529742,
      "lng": 5.447427
    },

    "Avignon": {
      "name": "Avignon",
      "ville_img": "img/villes/BBL_Avignon.jpg",
      "lat": 43.941557,
      "lng": 4.8332525
    },
```

Make sure you respect the alphabetical order when adding Bayonne. Lat/Lon must be the center of Bayonne ideally.

And send another PR to add the image for Bayonne: https://github.com/brownbaglunch/BrownBagLunch/tree/gh-pages/img/villes

2016-12-05 08:15 UTC, dadoonet commented on baggers.js
> +        "Paris, Pays basque"
It should be here:

```
"cities": [
        "Paris",
        "Bayonne"
      ]
```

2016-12-19 10:01 UTC, dadoonet commented
Ping?

2016-12-19 10:54 UTC, Yharra commented
Bonjour, 

oui, mais j’ai pas eu le temps de m’en occuper !


> Le 19 déc. 2016 à 11:01, David Pilato <notifications@github.com> a écrit :
> 
> Ping?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/brownbaglunch/bblfr_data/pull/155#issuecomment-267925582>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AFaxhGFGDIaU4y2KwIBuCbqTVVSOs-eYks5rJlXtgaJpZM4LDt5K>.
>

2017-04-01 20:37 UTC, dadoonet commented
Pas de News. Closing.

2017-04-01 20:37 UTC, closed without merging