feat(baggers): add Sébastien FRIESS
brownbaglunch/data pull request #200
Opened 2017-05-19 20:23 UTC by sebastienfr

Ajout Sébastien FRIESS.

2017-05-19 21:31 UTC, dadoonet requested changes
Juste quelques remarques de forme (indentation). Tu peux corriger ?

2017-05-19 21:31 UTC, dadoonet commented on baggers.js
> +          },
Petite indentation manquante je pense.

2017-05-19 21:31 UTC, dadoonet commented on baggers.js
> +              "title": "Microservice, comment peler le monolith et en faire de bonnes frites",
Pb d'indentation par rapport aux autres talks

2017-05-19 21:32 UTC, dadoonet commented
Et également à rebaser sur la dernière version. Merci !

2017-05-20 06:16 UTC, sebastienfr commented
@dadoonet ok. J'ai qqs différence en formatant le fichier sur intellij, je suppose que je fais les modifications que sur ma partie. Ok pour le rebase.

2017-05-22 10:04 UTC, sebastienfr commented
Rebased & fixed.

2017-05-26 21:20 UTC, sebastienfr commented
Up ;-)

2017-05-26 21:23 UTC, dadoonet reviewed
Pourquoi ton commit modifie entièrement un autre speaker? On ne devrait voir que ton ajout

2017-05-26 21:32 UTC, sebastienfr commented
Encore l'indentation, merdum :-( Pour info, elle a été cassée il y a qqs speaker, j'ai l'impression. Je me mets dans la suite. Sorry.

2017-05-26 21:39 UTC, sebastienfr commented
Alléluia, heureusement ce n'est pas du code et que du JSON ;-) Merci pout ta patience.

2017-05-26 21:53 UTC, dadoonet approved these changes

2017-05-26 21:53 UTC, merged

2017-05-26 21:54 UTC, dadoonet commented
Welcome!