add Christophe Furmaniak
brownbaglunch/data pull request #202
Opened 2017-06-05 10:00 UTC by looztra

2017-06-05 10:39 UTC, looztra commented
ouch, mince, mon éditeur a tout reformaté :(

2017-06-05 16:35 UTC, dadoonet requested changes
Tu peux annuler le formattage STP?

2017-06-06 05:06 UTC, looztra commented
done

2017-06-06 05:43 UTC, dadoonet approved these changes

2017-06-06 05:43 UTC, merged

2017-06-06 05:44 UTC, dadoonet commented
Bienvenue !

Si tu veux envoyer une seconde PR pour reformater tout le code, elle est la bienvenue :)