Ajout David DE CARVALHO
brownbaglunch/data pull request #214
Opened 2017-06-26 22:06 UTC by egry35

2017-06-27 04:30 UTC, dadoonet requested changes

2017-06-27 04:30 UTC, dadoonet commented on baggers.js
> +        "Viadeo": "http://www.viadeo.com/p/002typxcger1kb8"
Viadeo is not a supported contact. Must be in Websites part. See the Readme file.

2017-06-28 07:17 UTC, dadoonet approved these changes

2017-06-28 07:17 UTC, merged

2017-06-28 07:18 UTC, dadoonet commented
Bienvenue!

2017-07-04 14:58 UTC, egry35 commented
Merci :)