update email and talks
brownbaglunch/data pull request #250
Opened 2017-12-01 15:36 UTC by LaurentTardif

Bonjour,

je viens de mettre à jour mon email et les talls proposés

2017-12-01 18:04 UTC, dadoonet requested changes
I left some questions and remarks.
Could you fix the indentation problems please?

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +          "title": "Devops:",
`Devops:` is really the title of the talk or you are missing something?

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +			"Jenkins",
Could you please fix the indentation?

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +          "title": "Kubernetes:",
Same as previous. Why this `:` character which seems to tell that you wanted to add something.

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +		{
Indentation?

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +          "title": "Docker:",
Same for `:`

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +		{
Indentation?

2017-12-01 18:04 UTC, dadoonet commented on baggers.js
> +          "title": "Kafka:",
Same for `:`

2017-12-04 07:50 UTC, LaurentTardif commented
Salut David, j'ai corrigé l'indentation et changé un peu le titre pour devops pour le rendre un peu plus parlant.
Merci

2017-12-08 22:41 UTC, dadoonet approved these changes

2017-12-08 22:41 UTC, merged