Ajout de Olivier Wulveryck
brownbaglunch/data pull request #266
Opened 2018-01-25 16:26 UTC by owulveryck

Hello,

I have added myself to the baggers.js file.

Thanks

2018-01-25 17:43 UTC, dadoonet requested changes
You have a typo I think

2018-01-25 17:43 UTC, dadoonet commented on baggers.js
> +        },
I think this is wrong (comma).

2018-01-26 09:08 UTC, owulveryck reviewed
I have fixed the typo. Many thanks

2018-01-26 09:29 UTC, dadoonet approved these changes
Bienvenue!

2018-01-26 09:29 UTC, merged