new speaker : xavier blanc
brownbaglunch/data pull request #295
Opened 2018-06-09 15:43 UTC by xblanc33

Dear All,

Here is my modest contribution.

I hope the PR is ok.

Regards

X.B.

2018-06-09 16:29 UTC, dadoonet requested changes

2018-06-09 16:29 UTC, dadoonet commented on baggers.js
> +        websites: [
Websites is not part of contacts. Please remove that part.

2018-06-09 16:29 UTC, dadoonet commented on baggers.js
> +          name: 'YouTube',
Although YouTube is not part of the official list, I'm +1 to add it. (http://data.brownbaglunch.fr/#websites)

2018-06-09 18:03 UTC, dadoonet approved these changes
LMK if you want me to merge it as is.

2018-06-09 18:03 UTC, dadoonet commented on baggers.js
> +          name: 'Web',
I was unclear but YouTube was fine. We just need to change the README as well then the website to add the YouTube icon IIRC.

2018-06-22 14:51 UTC, xblanc33 commented
Should I do something ?

2018-06-23 06:06 UTC, dadoonet commented
> Should I do something ?

Oh sorry if I was unclear but I was waiting for an answer on:

> LMK if you want me to merge it as is.

Unfortunately, we merged some other talks in the meantime so whatever your answer is (I merge or you revert last change), you'll have to rebase onto master first to resolve the current conflict.
LMK when it's done and I'll be happy to merge it. :)

2018-08-03 12:22 UTC, closed without merging