mimoun-kissi bagger
brownbaglunch/data pull request #365
Opened 2019-04-06 16:18 UTC by MimounKissi

2019-04-06 16:26 UTC, dadoonet requested changes
I left some comments.

2019-04-06 16:26 UTC, dadoonet commented on baggers.js
> +          name: 'Biography',
This is not part of the standard names we documented in the readme. Could you fix it?

2019-04-06 16:26 UTC, dadoonet commented on baggers.js
> +          name: 'Calendly',
This is not part of the standard names we documented in the readme. Could you fix it?

2019-04-06 16:26 UTC, dadoonet commented on baggers.js
> +	{
NIT: could you fix the indentation?

2019-04-06 16:35 UTC, dadoonet requested changes
Could you remove the format changes you did on the other parts?

2019-04-06 16:43 UTC, MimounKissi commented
Done

2019-04-09 15:12 UTC, dadoonet commented
Still not good. You modified other profiles.

2019-04-10 10:41 UTC, dadoonet commented
Toujours pas bon. Regarde le diff dans GitHub. Tu touches toujours aux autres lignes.

2019-04-10 11:25 UTC, MimounKissi commented
Oui je viens de voir ça sur le diff du github, c'est incroyable pourtant je
ne vais qu'ajouter mon profil en fin de fichier ...

Bon désolé de t'avoir embêter ...

Le mer. 10 avr. 2019 à 12:41, David Pilato <notifications@github.com> a
écrit :

> Toujours pas bon. Regarde le diff dans GitHub. Tu touches toujours aux
> autres lignes.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/brownbaglunch/bblfr_data/pull/365#issuecomment-481638692>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AqPM8fDAHqEsnzjnVZUrC_xoAu9sVDrSks5vfb_qgaJpZM4cgSGD>
> .
>

2019-04-23 15:36 UTC, dadoonet commented
Je te propose que tu refasses une nouvelle tentative from scratch pour éviter toutes ces modifications.
Je ferme cette PR et te laisse en ouvrir une nouvelle. Ok?

2019-04-23 15:36 UTC, closed without merging

2019-04-23 16:54 UTC, MimounKissi commented
C’est noté merci beaucoup

Le mar. 23 avr. 2019 à 17:36, David Pilato <notifications@github.com> a
écrit :

> Je te propose que tu refasses une nouvelle tentative from scratch pour
> éviter toutes ces modifications.
> Je ferme cette PR et te laisse en ouvrir une nouvelle. Ok?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/brownbaglunch/bblfr_data/pull/365#issuecomment-485856923>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKR4Z4IMYSEZ7HARDLKVFH3PR4UJHANCNFSM4HEBEGBQ>
> .
>