Ajout de PALOIT
brownbaglunch/data pull request #390
Opened 2019-07-03 14:19 UTC by sboucherit

Description de Leonard Lys, Samy Boucherit ainsi que d'Arthur Micoulet

2019-07-03 14:37 UTC, dadoonet requested changes
I left some minor comments. Could you fix them?

2019-07-03 14:37 UTC, dadoonet commented on baggers.js
> +  "since": "2019-07-03",
Could you check the indentation?

2019-07-03 14:37 UTC, dadoonet commented on baggers.js
> +
Could you remove this change?

2019-07-05 11:54 UTC, sboucherit commented on baggers.js
> +
That should be solved ! Thank you

2019-07-05 19:28 UTC, dadoonet requested changes

2019-07-05 19:28 UTC, dadoonet commented on baggers.js
> -      since: '2015-03-10',
I don't understand why this is removed. Could you check?
Make sure you put also your addition at the end of the file.

2019-07-08 09:29 UTC, closed without merging