add(bagger): Fabien Hiegel as new bagger in Nantes
brownbaglunch/data pull request #458
Opened 2021-03-16 21:57 UTC by fhiegel

2021-04-06 16:32 UTC, dadoonet requested changes
Désolé pour le délai. peux-tu éventuellement fixer le minuscule pb d'indentation?

2021-04-06 16:32 UTC, dadoonet commented on baggers.js
> +{
NIT: fix this inden

2021-04-07 09:09 UTC, fhiegel commented on baggers.js
> +{
Done.

2021-04-07 09:10 UTC, fhiegel commented
Pas de soucis. Merci de prendre le temps en tout cas :)

Indentation corrigée.

2021-04-07 09:16 UTC, dadoonet approved these changes

2021-04-07 09:16 UTC, merged

2021-04-07 09:16 UTC, dadoonet commented
Welcome!